name: cmark-gfm-simple
version: 0.1.0
category: Text
license: BSD3
license-file: LICENSE.md
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

github: brandonchinn178/cmark-gfm-simple

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances
  - -Wno-unused-packages

library:
  source-dirs: src
  dependencies:
    - base < 5
    - cmark-gfm
    - text
