name: cmark-gfm-simple
version: 0.1.0
category: Text
license: BSD3
license-file: LICENSE.md
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
github: brandonchinn178/cmark-gfm-simple

extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances
  - -Wno-unused-packages

flags:
  ghc-syntax-highlighter:
    description: Add ghc-syntax-highlighter support
    default: false
    manual: true

library:
  source-dirs: src
  when:
    - condition: flag(ghc-syntax-highlighter)
      exposed-modules:
        - CMarkGFM.Simple.GhcSyntaxHighlighter
      dependencies:
        - ghc-syntax-highlighter-themed
  dependencies:
    - base < 5
    - cmark-gfm
    - text

tests:
  cmark-gfm-simple-tests:
    source-dirs: test
    main: Main.hs
    ghc-options: -F -pgmF=tasty-autocollect
    build-tools:
      - tasty-autocollect:tasty-autocollect
    dependencies:
      - base
      - cmark-gfm
      - cmark-gfm-simple
      - tasty
      - tasty-autocollect
      - tasty-golden
      - tasty-hunit
      - text
